"""
core/storage/database.py  --  Database Persistence for the DQ Pipeline
======================================================================
Handles:
  - Creating the schema (batch_runs, issues, quality_scores tables)
  - Writing pipeline results to PostgreSQL or SQLite
  - Querying historical batches and trends

Requires: sqlalchemy (pip install sqlalchemy psycopg2-binary)
For SQLite (local dev): no extra dependencies needed.
"""

import json
import logging
import os
from datetime import datetime, timezone
from typing import Dict, Any, Optional, List

import pandas as pd

logger = logging.getLogger("dq_engine.db")

# ---------------------------------------------------------------------------
# Shared engine cache (one connection pool per process)
# ---------------------------------------------------------------------------
_ENGINE_CACHE = {}


def get_engine(config: Dict[str, Any] = None):
    """
    Get a SQLAlchemy engine. Priority order:
    1. DATABASE_URL environment variable (used in ECS/production)
    2. Config dict (used when called from pipeline)
    3. Default SQLite fallback
    """
    from sqlalchemy import create_engine

    # 1. DATABASE_URL env var takes priority (set in ECS task definition)
    db_url = os.environ.get("DATABASE_URL")
    if db_url:
        cache_key = db_url
        if cache_key not in _ENGINE_CACHE:
            logger.info("Using DATABASE_URL from environment")
            _ENGINE_CACHE[cache_key] = create_engine(
                db_url,
                pool_size=5,
                max_overflow=10,
                pool_pre_ping=True,  # reconnect on stale connections
            )
        return _ENGINE_CACHE[cache_key]

    # 2. Config dict
    if config:
        return _get_engine(config)

    # 3. SQLite fallback
    os.makedirs("./output", exist_ok=True)
    url = "sqlite:///./output/dq_investigator.db"
    if url not in _ENGINE_CACHE:
        _ENGINE_CACHE[url] = create_engine(url)
    return _ENGINE_CACHE[url]

# ---------------------------------------------------------------------------
# Schema DDL — executed on first run or via migrate command
# ---------------------------------------------------------------------------
SCHEMA_SQL = """
-- Batch runs: one row per pipeline execution
CREATE TABLE IF NOT EXISTS batch_runs (
    batch_id        TEXT PRIMARY KEY,
    timestamp       TIMESTAMP NOT NULL,
    source_file     TEXT,
    rows_processed  INTEGER NOT NULL,
    columns         TEXT,                -- JSON array of column names
    overall_score   REAL NOT NULL,
    pass            BOOLEAN NOT NULL,
    pass_threshold  REAL NOT NULL,
    issues_count    INTEGER NOT NULL,
    llm_calls       INTEGER DEFAULT 0,
    data_sent_to_llm BOOLEAN DEFAULT FALSE,
    completeness    REAL,
    uniqueness      REAL,
    consistency     REAL,
    validity        REAL,
    accuracy        REAL,
    timeliness      REAL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Issues: one row per detected issue
CREATE TABLE IF NOT EXISTS issues (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    batch_id        TEXT NOT NULL REFERENCES batch_runs(batch_id),
    row_id          INTEGER,
    column_name     TEXT,
    issue_type      TEXT,
    detail          TEXT,
    severity        TEXT,
    value           TEXT,
    expected        TEXT,
    rule            TEXT,
    suggestion      TEXT,
    description     TEXT,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Audit trail: one row per pipeline step
CREATE TABLE IF NOT EXISTS audit_trail (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    batch_id        TEXT NOT NULL REFERENCES batch_runs(batch_id),
    step_name       TEXT NOT NULL,
    duration_ms     INTEGER,
    details         TEXT,                -- JSON blob for step-specific data
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index for fast batch lookups
CREATE INDEX IF NOT EXISTS idx_issues_batch ON issues(batch_id);
CREATE INDEX IF NOT EXISTS idx_audit_batch ON audit_trail(batch_id);
CREATE INDEX IF NOT EXISTS idx_batch_timestamp ON batch_runs(timestamp);

-- AI Enrichment: smart rules generated by AI
CREATE TABLE IF NOT EXISTS ai_smart_rules (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    batch_id        TEXT NOT NULL REFERENCES batch_runs(batch_id),
    column_name     TEXT,
    rule_type       TEXT,
    description     TEXT,
    condition_text  TEXT,
    confidence      REAL,
    reasoning       TEXT,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- AI Enrichment: cross-column issues
CREATE TABLE IF NOT EXISTS ai_cross_column (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    batch_id        TEXT NOT NULL REFERENCES batch_runs(batch_id),
    columns_involved TEXT,               -- JSON array of column names
    check_type      TEXT,
    description     TEXT,
    severity        TEXT,
    suggested_query TEXT,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- AI Enrichment: anomaly explanations
CREATE TABLE IF NOT EXISTS ai_explanations (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    batch_id        TEXT NOT NULL REFERENCES batch_runs(batch_id),
    column_name     TEXT,
    issue_type      TEXT,
    explanation     TEXT,
    business_impact TEXT,
    suggested_action TEXT,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- AI Enrichment: issue triage (priority-ranked)
CREATE TABLE IF NOT EXISTS ai_triage (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    batch_id        TEXT NOT NULL REFERENCES batch_runs(batch_id),
    priority        INTEGER,
    column_name     TEXT,
    issue_type      TEXT,
    issue_count     INTEGER,
    severity        TEXT,
    reason          TEXT,
    effort          TEXT,
    recommendation  TEXT,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- AI Enrichment: executive summary
CREATE TABLE IF NOT EXISTS ai_executive_summary (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    batch_id        TEXT NOT NULL REFERENCES batch_runs(batch_id),
    summary_text    TEXT NOT NULL,
    provider        TEXT,
    total_time_secs REAL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ai_smart_rules_batch ON ai_smart_rules(batch_id);
CREATE INDEX IF NOT EXISTS idx_ai_cross_column_batch ON ai_cross_column(batch_id);
CREATE INDEX IF NOT EXISTS idx_ai_explanations_batch ON ai_explanations(batch_id);
CREATE INDEX IF NOT EXISTS idx_ai_triage_batch ON ai_triage(batch_id);
CREATE INDEX IF NOT EXISTS idx_ai_exec_summary_batch ON ai_executive_summary(batch_id);

-- AI Audit Log: one row per AI call, tracks what was sent and what came back
CREATE TABLE IF NOT EXISTS ai_audit_log (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    batch_id         TEXT,
    call_type        VARCHAR(50),
    provider         VARCHAR(50),
    model            VARCHAR(100),
    payload_summary  TEXT,
    response_preview TEXT,
    tokens_used      INTEGER,
    response_time_ms INTEGER,
    raw_data_included BOOLEAN DEFAULT FALSE,
    pii_included      BOOLEAN DEFAULT FALSE,
    success           BOOLEAN DEFAULT TRUE,
    error_message     TEXT
);
CREATE INDEX IF NOT EXISTS idx_ai_audit_batch ON ai_audit_log(batch_id);
CREATE INDEX IF NOT EXISTS idx_ai_audit_time ON ai_audit_log(timestamp);

-- Corpus persistence: survive Redis restarts
CREATE TABLE IF NOT EXISTS corpus_store (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    corpus_name  VARCHAR(255) NOT NULL,
    corpus_type  VARCHAR(50)  NOT NULL,
    key_column   VARCHAR(255),
    value_column VARCHAR(255),
    csv_data     TEXT NOT NULL,
    loaded_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(corpus_name)
);
"""

# PostgreSQL version (uses SERIAL instead of AUTOINCREMENT)
SCHEMA_SQL_PG = SCHEMA_SQL.replace(
    "INTEGER PRIMARY KEY AUTOINCREMENT",
    "SERIAL PRIMARY KEY"
)


# ---------------------------------------------------------------------------
# Connection management
# ---------------------------------------------------------------------------
def _get_engine(config: Dict[str, Any]):
    """Create a SQLAlchemy engine from config dict."""
    from sqlalchemy import create_engine

    db_cfg = config.get("output", {}).get("database", {})
    engine_type = db_cfg.get("engine", "sqlite")

    if engine_type == "sqlite":
        db_path = db_cfg.get("path", "./output/dq_investigator.db")
        os.makedirs(os.path.dirname(os.path.abspath(db_path)), exist_ok=True)
        url = f"sqlite:///{db_path}"
        logger.info(f"Using SQLite: {db_path}")
    elif engine_type == "postgresql":
        host = db_cfg.get("host", "localhost")
        port = db_cfg.get("port", 5432)
        name = db_cfg.get("name", "dq_investigator")
        user = db_cfg.get("user", "")
        password = db_cfg.get("password", "")
        url = f"postgresql://{user}:{password}@{host}:{port}/{name}"
        logger.info(f"Using PostgreSQL: {host}:{port}/{name}")
    else:
        raise ValueError(f"Unsupported database engine: {engine_type}")

    if url not in _ENGINE_CACHE:
        kwargs = {"pool_pre_ping": True} if engine_type == "postgresql" else {}
        _ENGINE_CACHE[url] = create_engine(url, **kwargs)
    return _ENGINE_CACHE[url]


# ---------------------------------------------------------------------------
# Schema creation
# ---------------------------------------------------------------------------
def init_schema(config: Dict[str, Any]) -> None:
    """Create tables if they don't exist."""
    engine = get_engine(config)
    db_type = config.get("output", {}).get("database", {}).get("engine", "sqlite")

    sql = SCHEMA_SQL_PG if db_type == "postgresql" else SCHEMA_SQL

    with engine.connect() as conn:
        for statement in sql.split(";"):
            stmt = statement.strip()
            if stmt:
                conn.execute(conn.connection.cursor().execute(stmt) if False else __import__("sqlalchemy").text(stmt))
        conn.commit()

    logger.info("Database schema initialized")


def _init_schema_safe(engine, db_type: str = None) -> None:
    """Create tables using raw connection to avoid SQLAlchemy text() issues."""
    # Always detect from the actual engine URL — never trust the caller's config dict
    # which may say "sqlite" even when DATABASE_URL points to PostgreSQL.
    _engine_url = str(engine.url)
    _is_pg = "postgresql" in _engine_url or "postgres" in _engine_url
    sql = SCHEMA_SQL_PG if _is_pg else SCHEMA_SQL

    with engine.connect() as conn:
        from sqlalchemy import text
        for statement in sql.split(";"):
            stmt = statement.strip()
            if stmt:
                conn.execute(text(stmt))
        conn.commit()

    logger.info("Database schema initialized")


# ---------------------------------------------------------------------------
# WRITE — Save pipeline results to database
# ---------------------------------------------------------------------------
def save_results_to_db(
    result: Dict[str, Any],
    config: Dict[str, Any],
    source_file: str = "",
) -> Dict[str, int]:
    """
    Persist pipeline results to the database.
    Creates schema if tables don't exist.
    Returns dict with row counts written: {batch_runs, issues, audit_trail}.
    """
    engine = get_engine(config)
    db_type = config.get("output", {}).get("database", {}).get("engine", "sqlite")

    # Ensure schema exists
    _init_schema_safe(engine, db_type)

    counts = {}

    with engine.connect() as conn:
        from sqlalchemy import text

        # ── 1. batch_runs ──────────────────────────────────────────────────
        scores = result.get("quality_scores", {})
        conn.execute(text("""
            INSERT INTO batch_runs (
                batch_id, timestamp, source_file, rows_processed, columns,
                overall_score, pass, pass_threshold, issues_count,
                llm_calls, data_sent_to_llm,
                completeness, uniqueness, consistency, validity, accuracy, timeliness
            ) VALUES (
                :batch_id, :timestamp, :source_file, :rows_processed, :columns,
                :overall_score, :pass, :pass_threshold, :issues_count,
                :llm_calls, :data_sent_to_llm,
                :completeness, :uniqueness, :consistency, :validity, :accuracy, :timeliness
            )
        """), {
            "batch_id": result["batch_id"],
            "timestamp": result["timestamp"],
            "source_file": source_file,
            "rows_processed": result["rows_processed"],
            "columns": json.dumps(result["columns"]),
            "overall_score": float(result["overall_score"]),
            "pass": bool(result["pass"]),
            "pass_threshold": float(result["pass_threshold"]),
            "issues_count": int(result["issues_count"]),
            "llm_calls": int(result.get("llm_calls", 0)),
            "data_sent_to_llm": bool(result.get("data_sent_to_llm", False)),
            "completeness": float(scores.get("completeness", 0)),
            "uniqueness": float(scores.get("uniqueness", 0)),
            "consistency": float(scores.get("consistency", 0)),
            "validity": float(scores.get("validity", 0)),
            "accuracy": float(scores.get("accuracy", 0)),
            "timeliness": float(scores.get("timeliness", 0)),
        })
        counts["batch_runs"] = 1

        # ── 2. issues — bulk insert via to_sql (100x faster than iterrows) ──
        issues_df = result.get("issues", pd.DataFrame())
        issue_count = 0
        if not isinstance(issues_df, pd.DataFrame):
            issues_df = pd.DataFrame()
        if not issues_df.empty:
            # Normalise column names to what the DB expects
            _col_map = {
                "column": "column_name",
                "issue": "issue_type",
                "detail_technical": "detail",
                "source": "rule",
            }
            bulk = issues_df.rename(columns=_col_map).copy()
            bulk["batch_id"] = result["batch_id"]

            # Ensure required columns exist, truncate long strings
            def _col(df, name, default=""):
                return df[name] if name in df.columns else default

            bulk_rows = pd.DataFrame({
                "batch_id":    bulk["batch_id"],
                "row_id":      pd.to_numeric(_col(bulk, "row_id", 0), errors="coerce").fillna(0).astype(int),
                "column_name": _col(bulk, "column_name", "").astype(str).str[:100],
                "issue_type":  _col(bulk, "issue_type", "").astype(str).str[:100],
                "detail":      _col(bulk, "detail", "").astype(str).str[:500],
                "severity":    _col(bulk, "severity", "").astype(str).str[:50],
                "value":       _col(bulk, "value", "").astype(str).str[:200],
                "expected":    _col(bulk, "expected", "").astype(str).str[:200],
                "rule":        _col(bulk, "rule", "").astype(str).str[:200],
                "suggestion":  _col(bulk, "suggestion", "").astype(str).str[:200],
                "description": _col(bulk, "description", "").astype(str).str[:500],
            })

            # to_sql uses executemany under the hood — single round-trip per chunk
            bulk_rows.to_sql(
                "issues",
                conn,
                if_exists="append",
                index=False,
                chunksize=500,   # 500 rows per INSERT batch
                method="multi",  # single multi-value INSERT statement per chunk
            )
            issue_count = len(bulk_rows)
        counts["issues"] = issue_count

        # ── 3. audit_trail ─────────────────────────────────────────────────
        audit_count = 0
        for step in result.get("audit_trail", []):
            step_name = step.pop("step", "unknown")
            duration = step.pop("duration_ms", 0)
            conn.execute(text("""
                INSERT INTO audit_trail (batch_id, step_name, duration_ms, details)
                VALUES (:batch_id, :step_name, :duration_ms, :details)
            """), {
                "batch_id": result["batch_id"],
                "step_name": step_name,
                "duration_ms": int(duration),
                "details": json.dumps(step),
            })
            # Restore popped keys for other consumers
            step["step"] = step_name
            step["duration_ms"] = duration
            audit_count += 1
        counts["audit_trail"] = audit_count

        conn.commit()

    logger.info(
        f"Database write complete: 1 batch, {counts['issues']} issues, "
        f"{counts['audit_trail']} audit steps"
    )
    return counts


# ---------------------------------------------------------------------------
# READ — Query historical data
# ---------------------------------------------------------------------------
def get_recent_batches(
    config: Dict[str, Any],
    limit: int = 20,
) -> pd.DataFrame:
    """Get the most recent batch runs, ordered by timestamp descending."""
    engine = get_engine(config)
    query = f"""
        SELECT batch_id, timestamp, source_file, rows_processed,
               overall_score, pass, issues_count,
               completeness, uniqueness, consistency, validity, accuracy, timeliness
        FROM batch_runs
        ORDER BY timestamp DESC
        LIMIT {limit}
    """
    return pd.read_sql(query, engine)


def get_batch_issues(
    config: Dict[str, Any],
    batch_id: str,
) -> pd.DataFrame:
    """Get all issues for a specific batch."""
    engine = get_engine(config)
    from sqlalchemy import text
    query = text("""
        SELECT row_id, column_name, issue_type, detail, severity,
               value, expected, suggestion, description
        FROM issues
        WHERE batch_id = :batch_id
        ORDER BY row_id, column_name
    """)
    return pd.read_sql(query, engine, params={"batch_id": batch_id})


def get_score_trend(
    config: Dict[str, Any],
    limit: int = 50,
) -> pd.DataFrame:
    """Get quality score trend over time."""
    engine = get_engine(config)
    query = f"""
        SELECT batch_id, timestamp, overall_score, pass,
               completeness, uniqueness, consistency, validity, accuracy, timeliness
        FROM batch_runs
        ORDER BY timestamp DESC
        LIMIT {limit}
    """
    df = pd.read_sql(query, engine)
    return df.sort_values("timestamp")  # chronological order


def get_batch_audit(
    config: Dict[str, Any],
    batch_id: str,
) -> pd.DataFrame:
    """Get audit trail for a specific batch."""
    engine = get_engine(config)
    from sqlalchemy import text
    query = text("""
        SELECT step_name, duration_ms, details, created_at
        FROM audit_trail
        WHERE batch_id = :batch_id
        ORDER BY id
    """)
    return pd.read_sql(query, engine, params={"batch_id": batch_id})


# ---------------------------------------------------------------------------
# WRITE — Save AI enrichment results
# ---------------------------------------------------------------------------
def save_ai_enrichment(
    batch_id: str,
    enrichment_result: Any,
    config: Dict[str, Any],
) -> Dict[str, int]:
    """
    Persist AI enrichment results to the database.

    Args:
        batch_id: The batch this enrichment belongs to.
        enrichment_result: An EnrichmentResult dataclass from ai_enrichment module.
        config: Database configuration dict.

    Returns:
        Dict with counts of rows written per table.
    """
    engine = get_engine(config)
    _db_url = os.environ.get("DATABASE_URL", "")
    db_type = "postgresql" if ("postgresql" in _db_url or "postgres" in _db_url) else config.get("output", {}).get("database", {}).get("engine", "sqlite")
    _init_schema_safe(engine, db_type)

    counts = {}

    with engine.connect() as conn:
        from sqlalchemy import text

        # -- Smart Rules --
        sr_count = 0
        for rule in (enrichment_result.smart_rules or []):
            if isinstance(rule, dict) and "raw" not in rule:
                conn.execute(text("""
                    INSERT INTO ai_smart_rules
                        (batch_id, column_name, rule_type, description, condition_text, confidence, reasoning)
                    VALUES
                        (:batch_id, :column_name, :rule_type, :description, :condition_text, :confidence, :reasoning)
                """), {
                    "batch_id": batch_id,
                    "column_name": str(rule.get("column", ""))[:100],
                    "rule_type": str(rule.get("rule_type", ""))[:50],
                    "description": str(rule.get("description", ""))[:500],
                    "condition_text": str(rule.get("condition", ""))[:500],
                    "confidence": float(rule.get("confidence", 0)),
                    "reasoning": str(rule.get("reasoning", ""))[:500],
                })
                sr_count += 1
        counts["ai_smart_rules"] = sr_count

        # -- Cross-Column Issues --
        cc_count = 0
        for issue in (enrichment_result.cross_column_issues or []):
            if isinstance(issue, dict):
                cols_involved = issue.get("columns", [])
                if isinstance(cols_involved, str):
                    cols_involved = [cols_involved]
                conn.execute(text("""
                    INSERT INTO ai_cross_column
                        (batch_id, columns_involved, check_type, description, severity, suggested_query)
                    VALUES
                        (:batch_id, :columns_involved, :check_type, :description, :severity, :suggested_query)
                """), {
                    "batch_id": batch_id,
                    "columns_involved": json.dumps(cols_involved),
                    "check_type": str(issue.get("check_type", ""))[:100],
                    "description": str(issue.get("description", ""))[:500],
                    "severity": str(issue.get("severity", "medium"))[:20],
                    "suggested_query": str(issue.get("suggested_query", ""))[:500],
                })
                cc_count += 1
        counts["ai_cross_column"] = cc_count

        # -- Anomaly Explanations --
        ex_count = 0
        for exp in (enrichment_result.explanations or []):
            if isinstance(exp, dict):
                conn.execute(text("""
                    INSERT INTO ai_explanations
                        (batch_id, column_name, issue_type, explanation, business_impact, suggested_action)
                    VALUES
                        (:batch_id, :column_name, :issue_type, :explanation, :business_impact, :suggested_action)
                """), {
                    "batch_id": batch_id,
                    "column_name": str(exp.get("column", ""))[:100],
                    "issue_type": str(exp.get("issue_type", ""))[:100],
                    "explanation": str(exp.get("explanation", ""))[:1000],
                    "business_impact": str(exp.get("business_impact", ""))[:500],
                    "suggested_action": str(exp.get("suggested_action", ""))[:500],
                })
                ex_count += 1
        counts["ai_explanations"] = ex_count

        # -- Issue Triage --
        tr_count = 0
        for item in (enrichment_result.triage or []):
            if isinstance(item, dict):
                conn.execute(text("""
                    INSERT INTO ai_triage
                        (batch_id, priority, column_name, issue_type, issue_count, severity, reason, effort, recommendation)
                    VALUES
                        (:batch_id, :priority, :column_name, :issue_type, :issue_count, :severity, :reason, :effort, :recommendation)
                """), {
                    "batch_id": batch_id,
                    "priority": int(item.get("priority", 99)),
                    "column_name": str(item.get("column", ""))[:100],
                    "issue_type": str(item.get("issue_type", ""))[:100],
                    "issue_count": int(item.get("count", 0)),
                    "severity": str(item.get("severity", "medium"))[:20],
                    "reason": str(item.get("reason", ""))[:500],
                    "effort": str(item.get("effort", ""))[:50],
                    "recommendation": str(item.get("recommendation", ""))[:500],
                })
                tr_count += 1
        counts["ai_triage"] = tr_count

        # -- Executive Summary --
        es_count = 0
        summary_text = enrichment_result.executive_summary or ""
        if summary_text.strip():
            conn.execute(text("""
                INSERT INTO ai_executive_summary
                    (batch_id, summary_text, provider, total_time_secs)
                VALUES
                    (:batch_id, :summary_text, :provider, :total_time_secs)
            """), {
                "batch_id": batch_id,
                "summary_text": summary_text[:5000],
                "provider": str(enrichment_result.provider or ""),
                "total_time_secs": round(enrichment_result.total_time_seconds, 2),
            })
            es_count = 1
        counts["ai_executive_summary"] = es_count

        conn.commit()

    logger.info(
        "AI enrichment saved: %d rules, %d cross-col, %d explanations, %d triage, %d summary",
        counts["ai_smart_rules"], counts["ai_cross_column"],
        counts["ai_explanations"], counts["ai_triage"], counts["ai_executive_summary"],
    )
    return counts


# ---------------------------------------------------------------------------
# READ — Query AI enrichment data
# ---------------------------------------------------------------------------
def get_ai_smart_rules(config: Dict[str, Any], batch_id: str) -> pd.DataFrame:
    """Get AI-generated smart rules for a batch."""
    engine = get_engine(config)
    from sqlalchemy import text
    query = text("""
        SELECT column_name, rule_type, description, condition_text, confidence, reasoning
        FROM ai_smart_rules
        WHERE batch_id = :batch_id
        ORDER BY confidence DESC
    """)
    return pd.read_sql(query, engine, params={"batch_id": batch_id})


def get_ai_cross_column(config: Dict[str, Any], batch_id: str) -> pd.DataFrame:
    """Get AI cross-column analysis for a batch."""
    engine = get_engine(config)
    from sqlalchemy import text
    query = text("""
        SELECT columns_involved, check_type, description, severity, suggested_query
        FROM ai_cross_column
        WHERE batch_id = :batch_id
        ORDER BY CASE severity
            WHEN 'critical' THEN 1 WHEN 'high' THEN 2
            WHEN 'medium' THEN 3 WHEN 'low' THEN 4 ELSE 5 END
    """)
    return pd.read_sql(query, engine, params={"batch_id": batch_id})


def get_ai_explanations(config: Dict[str, Any], batch_id: str) -> pd.DataFrame:
    """Get AI anomaly explanations for a batch."""
    engine = get_engine(config)
    from sqlalchemy import text
    query = text("""
        SELECT column_name, issue_type, explanation, business_impact, suggested_action
        FROM ai_explanations
        WHERE batch_id = :batch_id
        ORDER BY id
    """)
    return pd.read_sql(query, engine, params={"batch_id": batch_id})


def get_ai_triage(config: Dict[str, Any], batch_id: str) -> pd.DataFrame:
    """Get AI issue triage for a batch."""
    engine = get_engine(config)
    from sqlalchemy import text
    query = text("""
        SELECT priority, column_name, issue_type, issue_count, severity, reason, effort, recommendation
        FROM ai_triage
        WHERE batch_id = :batch_id
        ORDER BY priority ASC
    """)
    return pd.read_sql(query, engine, params={"batch_id": batch_id})


def get_ai_executive_summary(config: Dict[str, Any], batch_id: str) -> Optional[str]:
    """Get AI executive summary for a batch. Returns the summary text or None."""
    engine = get_engine(config)
    from sqlalchemy import text
    query = text("""
        SELECT summary_text, provider, total_time_secs
        FROM ai_executive_summary
        WHERE batch_id = :batch_id
        ORDER BY created_at DESC
        LIMIT 1
    """)
    df = pd.read_sql(query, engine, params={"batch_id": batch_id})
    if df.empty:
        return None
    return df.iloc[0]["summary_text"]


def get_batches_with_ai(config: Dict[str, Any], limit: int = 20) -> List[str]:
    """Get batch IDs that have AI enrichment data."""
    engine = get_engine(config)
    from sqlalchemy import text
    query = text("""
        SELECT DISTINCT batch_id FROM ai_executive_summary
        ORDER BY created_at DESC
        LIMIT :limit
    """)
    df = pd.read_sql(query, engine, params={"limit": limit})
    return df["batch_id"].tolist() if not df.empty else []


# ---------------------------------------------------------------------------
# CORPUS PERSISTENCE — save/load corpus data to/from RDS
# ---------------------------------------------------------------------------

def save_corpus_to_db(
    corpus_name: str,
    corpus_type: str,
    key_column: str,
    value_column: str,
    df: "pd.DataFrame",
) -> None:
    """
    Persist a corpus DataFrame to the corpus_store table (upsert on corpus_name).

    Args:
        corpus_name:  Unique name for the corpus (used as the upsert key).
        corpus_type:  One of 'alias', 'lookup', 'validation'.
        key_column:   Name of the key column in the DataFrame.
        value_column: Name of the value column in the DataFrame.
        df:           The corpus DataFrame to store as CSV text.
    """
    import io
    from sqlalchemy import text

    engine = get_engine()
    db_url = os.environ.get("DATABASE_URL", "")
    is_pg = db_url.startswith("postgresql") or db_url.startswith("postgres")

    # Ensure corpus_store table exists
    schema_sql = SCHEMA_SQL_PG if is_pg else SCHEMA_SQL
    with engine.connect() as conn:
        for stmt in schema_sql.split(";"):
            s = stmt.strip()
            if s:
                conn.execute(text(s))
        conn.commit()

    csv_text = df.to_csv(index=False)

    with engine.connect() as conn:
        if is_pg:
            conn.execute(text("""
                INSERT INTO corpus_store (corpus_name, corpus_type, key_column, value_column, csv_data, loaded_at)
                VALUES (:corpus_name, :corpus_type, :key_column, :value_column, :csv_data, NOW())
                ON CONFLICT (corpus_name) DO UPDATE SET
                    corpus_type  = EXCLUDED.corpus_type,
                    key_column   = EXCLUDED.key_column,
                    value_column = EXCLUDED.value_column,
                    csv_data     = EXCLUDED.csv_data,
                    loaded_at    = NOW()
            """), {
                "corpus_name": corpus_name,
                "corpus_type": corpus_type,
                "key_column": key_column,
                "value_column": value_column,
                "csv_data": csv_text,
            })
        else:
            # SQLite fallback — INSERT OR REPLACE respects UNIQUE constraint
            conn.execute(text("""
                INSERT OR REPLACE INTO corpus_store
                    (corpus_name, corpus_type, key_column, value_column, csv_data, loaded_at)
                VALUES
                    (:corpus_name, :corpus_type, :key_column, :value_column, :csv_data, CURRENT_TIMESTAMP)
            """), {
                "corpus_name": corpus_name,
                "corpus_type": corpus_type,
                "key_column": key_column,
                "value_column": value_column,
                "csv_data": csv_text,
            })
        conn.commit()

    logger.info("Corpus '%s' saved to database (%d rows)", corpus_name, len(df))


def load_all_corpus_from_db() -> List[Dict]:
    """
    Load all corpora from the corpus_store table.

    Returns:
        List of dicts, each with keys:
            corpus_name, corpus_type, key_column, value_column, df (pd.DataFrame)
        Returns an empty list if the table does not exist or is empty.
    """
    import io
    from sqlalchemy import text

    engine = get_engine()

    try:
        with engine.connect() as conn:
            result = conn.execute(text(
                "SELECT corpus_name, corpus_type, key_column, value_column, csv_data "
                "FROM corpus_store ORDER BY loaded_at ASC"
            ))
            rows = result.fetchall()
    except Exception:
        # Table may not exist yet (first run before any corpus is saved)
        logger.debug("corpus_store table not found or inaccessible — returning empty list")
        return []

    corpora = []
    for row in rows:
        corpus_name, corpus_type, key_column, value_column, csv_data = row
        try:
            df = pd.read_csv(io.StringIO(csv_data))
            corpora.append({
                "corpus_name": corpus_name,
                "corpus_type": corpus_type,
                "key_column": key_column,
                "value_column": value_column,
                "df": df,
            })
        except Exception as e:
            logger.warning("Failed to restore corpus '%s' from DB: %s", corpus_name, e)

    logger.info("Loaded %d corpus record(s) from database", len(corpora))
    return corpora


# ---------------------------------------------------------------------------
# AI AUDIT LOG — log every AI call for compliance and transparency
# ---------------------------------------------------------------------------

def log_ai_call(
    batch_id: str,
    call_type: str,
    provider: str,
    model: str,
    payload_summary: str,
    response_preview: str,
    tokens_used: int,
    response_time_ms: int,
    success: bool = True,
    error_message: Optional[str] = None,
) -> None:
    """
    Log an AI call to the ai_audit_log table.
    Silently fails if DB unavailable — never breaks the calling enrichment.

    Args:
        batch_id:         The batch this call belongs to.
        call_type:        One of: smart_rules, cross_column, anomaly_explanation,
                          issue_triage, executive_summary.
        provider:         LLM provider name (anthropic, bedrock, ollama).
        model:            Model identifier string.
        payload_summary:  JSON string describing WHAT STATISTICS were sent (no raw data).
        response_preview: First 500 chars of the LLM response.
        tokens_used:      Token count if available (0 if unknown).
        response_time_ms: Wall-clock time for the LLM call in milliseconds.
        success:          Whether the call completed without error.
        error_message:    Error details if success=False.
    """
    try:
        engine = get_engine()
        db_url = os.environ.get("DATABASE_URL", "")
        is_pg = db_url.startswith("postgresql") or db_url.startswith("postgres")

        # Ensure the table exists (applies the full schema, which is idempotent)
        schema_sql = SCHEMA_SQL_PG if is_pg else SCHEMA_SQL
        with engine.connect() as conn:
            from sqlalchemy import text as _text
            for stmt in schema_sql.split(";"):
                s = stmt.strip()
                if s:
                    try:
                        conn.execute(_text(s))
                    except Exception:
                        pass  # table already exists — ignore
            conn.commit()

        with engine.connect() as conn:
            from sqlalchemy import text as _text
            if is_pg:
                conn.execute(_text("""
                    INSERT INTO ai_audit_log (
                        timestamp, batch_id, call_type, provider, model,
                        payload_summary, response_preview, tokens_used,
                        response_time_ms, raw_data_included, pii_included,
                        success, error_message
                    ) VALUES (
                        NOW(), :batch_id, :call_type, :provider, :model,
                        :payload_summary, :response_preview, :tokens_used,
                        :response_time_ms, FALSE, FALSE,
                        :success, :error_message
                    )
                """), {
                    "batch_id": batch_id,
                    "call_type": call_type[:50] if call_type else None,
                    "provider": provider[:50] if provider else None,
                    "model": model[:100] if model else None,
                    "payload_summary": payload_summary,
                    "response_preview": (response_preview or "")[:500],
                    "tokens_used": int(tokens_used) if tokens_used else 0,
                    "response_time_ms": int(response_time_ms) if response_time_ms else 0,
                    "success": bool(success),
                    "error_message": error_message,
                })
            else:
                conn.execute(_text("""
                    INSERT INTO ai_audit_log (
                        timestamp, batch_id, call_type, provider, model,
                        payload_summary, response_preview, tokens_used,
                        response_time_ms, raw_data_included, pii_included,
                        success, error_message
                    ) VALUES (
                        CURRENT_TIMESTAMP, :batch_id, :call_type, :provider, :model,
                        :payload_summary, :response_preview, :tokens_used,
                        :response_time_ms, 0, 0,
                        :success, :error_message
                    )
                """), {
                    "batch_id": batch_id,
                    "call_type": call_type[:50] if call_type else None,
                    "provider": provider[:50] if provider else None,
                    "model": model[:100] if model else None,
                    "payload_summary": payload_summary,
                    "response_preview": (response_preview or "")[:500],
                    "tokens_used": int(tokens_used) if tokens_used else 0,
                    "response_time_ms": int(response_time_ms) if response_time_ms else 0,
                    "success": bool(success),
                    "error_message": error_message,
                })
            conn.commit()

        logger.debug("AI audit log: %s / %s / %s (%dms)", batch_id, call_type, provider, response_time_ms)

    except Exception as exc:
        # Never let logging break the calling enrichment
        logger.debug("AI audit log write failed (non-fatal): %s", exc)
